no-resolv
server=1.1.1.1
address=/cbfs01.gridshield.local/10.1.1.5
address=/novasec.gridshield.local/10.1.1.20
address=/vpn-gw.gridshield.local/10.1.1.10
address=/devstation.gridshield.local/10.1.1.15
address=/update.gridvault-records.test/198.51.100.20
address=/ftp.gridvault-records.test/198.51.100.20
address=/novasec-public.test/198.51.100.20
address=/blue-transit-vpn.test/192.0.2.10
address=/operator-workstation.test/198.18.45.23
